import { mkdir, writeFile, cp } from 'fs/promises'
import { existsSync } from 'fs'
import { join } from 'path'
import { MODULES_SRC } from './modules.js'

// .../services/node-app/src — источник db.js/loader.js при модульной сборке
const TEMPLATE_SRC = join(MODULES_SRC, '..')

const slug = name =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

// ── .env ──────────────────────────────────────────────────────────────────────

function env(a) {
  const db = slug(a.projectName)
  return `# Generated by ez-launch v0.1.0
# Project: ${a.projectName}

# ── Database ──────────────────────────────────────────────────────────────────
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=${db}
POSTGRES_USER=${db}
POSTGRES_PASSWORD=${a.postgresPassword}

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_URL=redis://redis:6379

# ── Node app ──────────────────────────────────────────────────────────────────
NODE_PORT=3000
NODE_ENV=${a.nodeEnv}

# ── Python app ────────────────────────────────────────────────────────────────
PYTHON_PORT=8000

# ── App ───────────────────────────────────────────────────────────────────────
APP_SECRET=${a.appSecret}
`
}

function envExample() {
  return `# ── Database ──────────────────────────────────────────────────────────────────
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=ezlaunch
POSTGRES_USER=ezl
POSTGRES_PASSWORD=changeme

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_URL=redis://redis:6379

# ── Node app ──────────────────────────────────────────────────────────────────
NODE_PORT=3000
NODE_ENV=development

# ── Python app ────────────────────────────────────────────────────────────────
PYTHON_PORT=8000

# ── App ───────────────────────────────────────────────────────────────────────
APP_SECRET=change-me-in-production
`
}

// ── Infrastructure files ──────────────────────────────────────────────────────

function dockerCompose() {
  return `services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      node-app:
        condition: service_started
      python-app:
        condition: service_started
    restart: unless-stopped

  node-app:
    build: ./services/node-app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/node-app:/app
      - /app/node_modules
    restart: unless-stopped

  python-app:
    build: ./services/python-app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/python-app:/app
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: \${POSTGRES_DB:-ezlaunch}
      POSTGRES_USER: \${POSTGRES_USER:-ezl}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-ezl} -d \${POSTGRES_DB:-ezlaunch}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  caddy_data:
`
}

function caddyfile(domain) {
  const host = domain === 'localhost' ? ':80' : domain
  return `{
    admin off
}

${host} {
    handle /ai/* {
        reverse_proxy python-app:8000
    }

    handle /api/* {
        reverse_proxy node-app:3000
    }

    handle /health/node {
        reverse_proxy node-app:3000/health
    }

    handle /health/python {
        reverse_proxy python-app:8000/health
    }

    handle {
        reverse_proxy node-app:3000
    }
}
`
}

function makefile() {
  const t = '\t'
  return `.PHONY: up down logs build test shell-node shell-python

up:
${t}cp -n .env.example .env 2>/dev/null || true
${t}docker compose up --build -d

down:
${t}docker compose down

logs:
${t}docker compose logs -f

build:
${t}docker compose build

test:
${t}docker compose run --rm node-app npm test
${t}docker compose run --rm python-app pytest

shell-node:
${t}docker compose exec node-app sh

shell-python:
${t}docker compose exec python-app bash
`
}

function gitignore() {
  return `.env
node_modules/
__pycache__/
*.pyc
.DS_Store
`
}

// ── Node service stubs ────────────────────────────────────────────────────────

function nodeDockerfile() {
  return `FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY src/ ./src/
EXPOSE 3000
CMD ["node", "src/index.js"]
`
}

function nodePackageJson(name) {
  return JSON.stringify({
    name: slug(name),
    version: '0.1.0',
    type: 'module',
    scripts: {
      start: 'node src/index.js',
      dev: 'node --watch src/index.js',
      lint: 'eslint src/',
      test: 'node --test src/**/*.test.js'
    },
    dependencies: { fastify: '^4.28.0' },
    devDependencies: { eslint: '^9.0.0' }
  }, null, 2) + '\n'
}

function nodeIndexJs() {
  return `import Fastify from 'fastify'

const app = Fastify({ logger: true })
const PORT = process.env.NODE_PORT || 3000

app.get('/health', async () => ({
  status: 'ok',
  service: 'node',
  version: '0.1.0'
}))

await app.listen({ port: PORT, host: '0.0.0.0' })
`
}

function nodeEslintrc() {
  return JSON.stringify({
    env: { es2022: true, node: true },
    parserOptions: { ecmaVersion: 2022, sourceType: 'module' },
    rules: { 'no-unused-vars': 'warn', 'no-console': 'off' }
  }, null, 2) + '\n'
}

// ── Python service stubs ──────────────────────────────────────────────────────

function pythonDockerfile() {
  return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src/
EXPOSE 8000
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
`
}

function pythonRequirements() {
  return `fastapi==0.111.0
uvicorn[standard]==0.30.0
`
}

function pythonMainPy() {
  return `from fastapi import FastAPI

app = FastAPI()


@app.get("/health")
def health():
    return {"status": "ok", "service": "python", "version": "0.1.0"}
`
}

// ── Main export ───────────────────────────────────────────────────────────────

function nodeIndexModular() {
  return `import Fastify from 'fastify'
import fjwt from '@fastify/jwt'
import cors from '@fastify/cors'
import Redis from 'ioredis'
import { pool, runMigrations } from './db.js'
import { loadModules } from './modules/loader.js'

const PORT = process.env.NODE_PORT || 3000
const app = Fastify({ logger: true })

await app.register(cors, {
  origin: ['http://localhost:5173', 'http://localhost:3000', process.env.FRONTEND_URL].filter(Boolean),
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
})

await app.register(fjwt, { secret: process.env.APP_SECRET || 'dev-secret-change-me' })

app.decorate('db', pool)
app.decorate('redis', new Redis(process.env.REDIS_URL || 'redis://redis:6379'))

// авто-дискавери модулей (выбраны на ez-launch init)
const loaded = await loadModules(app)

app.get('/health', async () => ({ status: 'ok', service: 'node', version: '0.1.0' }))
app.get('/api/modules', async () => loaded.manifest)

await runMigrations(loaded.migrationsDirs)

await app.listen({ port: PORT, host: '0.0.0.0' })
`
}

function nodePackageJsonModular(name) {
  return JSON.stringify({
    name: slug(name),
    version: '0.1.0',
    type: 'module',
    scripts: {
      start: 'node src/index.js',
      dev: 'node --watch src/index.js',
      lint: 'eslint src/',
      test: 'node --test src/**/*.test.js'
    },
    dependencies: {
      '@fastify/cors': '^10.0.0',
      '@fastify/jwt': '^9.0.0',
      bcrypt: '^5.1.1',
      fastify: '^5.0.0',
      ioredis: '^5.4.0',
      nodemailer: '^6.9.0',
      pg: '^8.13.0'
    },
    devDependencies: { eslint: '^9.0.0' }
  }, null, 2) + '\n'
}

// досборка модульного node-app поверх заглушки: db.js + loader.js + выбранные модули
async function emitModules(projectName, modules) {
  const nodeSrc = join(projectName, 'services', 'node-app', 'src')
  await mkdir(join(nodeSrc, 'modules'), { recursive: true })
  await cp(join(TEMPLATE_SRC, 'db.js'), join(nodeSrc, 'db.js'))
  await cp(join(MODULES_SRC, 'loader.js'), join(nodeSrc, 'modules', 'loader.js'))
  for (const name of modules) {
    await cp(join(MODULES_SRC, name), join(nodeSrc, 'modules', name), { recursive: true })
  }
  await writeFile(join(nodeSrc, 'index.js'), nodeIndexModular())
  await writeFile(join(projectName, 'services', 'node-app', 'package.json'), nodePackageJsonModular(projectName))
}

export async function generate(projectName, answers) {
  if (existsSync(projectName)) {
    throw new Error(`Directory "${projectName}" already exists`)
  }

  const d = (...parts) => join(projectName, ...parts)

  await mkdir(d('services', 'node-app', 'src'), { recursive: true })
  await mkdir(d('services', 'python-app', 'src'), { recursive: true })

  await Promise.all([
    // Root infra
    writeFile(d('.env'), env(answers)),
    writeFile(d('.env.example'), envExample()),
    writeFile(d('docker-compose.yml'), dockerCompose()),
    writeFile(d('Caddyfile'), caddyfile(answers.domain)),
    writeFile(d('Makefile'), makefile()),
    writeFile(d('.gitignore'), gitignore()),
    // Node service
    writeFile(d('services', 'node-app', 'Dockerfile'), nodeDockerfile()),
    writeFile(d('services', 'node-app', 'package.json'), nodePackageJson(projectName)),
    writeFile(d('services', 'node-app', 'src', 'index.js'), nodeIndexJs()),
    writeFile(d('services', 'node-app', '.eslintrc.json'), nodeEslintrc()),
    // Python service
    writeFile(d('services', 'python-app', 'Dockerfile'), pythonDockerfile()),
    writeFile(d('services', 'python-app', 'requirements.txt'), pythonRequirements()),
    writeFile(d('services', 'python-app', 'src', 'main.py'), pythonMainPy()),
  ])

  // EZL-US-010: выбраны модули — дособираем модульный node-app поверх заглушки
  if (answers.modules?.length) {
    await emitModules(projectName, answers.modules)
  }
}
